services:
    simple_page_builder.discriminator_map.listener:
        class: KunicMarko\SimplePageBuilderBundle\EventListener\DiscriminatorMapListener
        arguments: ["%simple_page_builder.types%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    simple_page_builder_types.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\AbstractTypeAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\AbstractType, SimplePageBuilderBundle:AbstractTypeCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false}
        calls:
            - [ setSubClasses, ["%simple_page_builder.types%"] ]

    simple_page_builder.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\PageBuilderAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\PageBuilder, SimplePageBuilderBundle:PageBuilderCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin , show_in_dashboard: false}

    simple_page_builder_has_type.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\PageBuilderHasTypeAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\PageBuilderHasType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin , show_in_dashboard: false}