services:
    simple_page_builder_types.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\AbstractTypeAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\AbstractType, SimplePageBuilderBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false}
        calls:
            - [ setSubClasses, ["%simple_page_builder.types%"] ]

    simple_page_builder.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\PageBuilderAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\PageBuilder, SimplePageBuilderBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin , show_in_dashboard: false}

    simple_page_builder_has_type.admin:
        class: KunicMarko\SimplePageBuilderBundle\Admin\PageBuilderHasTypeAdmin
        arguments: [~, KunicMarko\SimplePageBuilderBundle\Entity\PageBuilderHasType, SimplePageBuilderBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin , show_in_dashboard: false}
